### ISSUE TITLE
'Graph' object has no attribute 'release_resources'

### ISSUE THREAD

**Issue by cboulay** [qusp/orange3#3]
Probably related to a recent commit (https://github.com/qusp/vpe/commit/11716110c10be62f9bd043493e0e4b0a57e18714).

When I run vpe, I'm greeted with the Welcome widget (New, Open, Recent etc.). I can go through the steps of selecting New, naming it, then click on OK. As soon as I do, the Welcome widget reappears and I get the following error in console:

```
Traceback (most recent call last):
  File "/Volumes/STORE/Tools/Neurophys/NeuroPype/vpe/Orange/canvas/application/canvasmain.py", line 1515, in new_scheme
    if self.new_scheme() == QDialog.Accepted:
  File "/Volumes/STORE/Tools/Neurophys/NeuroPype/vpe/Orange/canvas/application/canvasmain.py", line 900, in new_scheme
    self.set_new_scheme(new_scheme)
  File "/Volumes/STORE/Tools/Neurophys/NeuroPype/vpe/Orange/canvas/application/canvasmain.py", line 1050, in set_new_scheme
    scheme_doc.setScheme(new_scheme)
  File "/Volumes/STORE/Tools/Neurophys/NeuroPype/vpe/Orange/canvas/document/schemeedit.py", line 595, in setScheme
    self.__scheme.release_resources()
  File "/Volumes/STORE/Tools/Neurophys/NeuroPype/vpe/Orange/canvas/scheme/widgetsscheme.py", line 112, in release_resources
    self.signal_manager.graph.release_resources()
AttributeError: 'Graph' object has no attribute 'release_resources'
```

**Comment by cboulay** [comment]
Some additional details...

If I revert to a commit before that one then the widget does disappear. Maybe informative: the original Welcome widget reappears for a moment after the name dialog widget disappears before it too disappears.

I can close the widget with the red circle on the top left of the window and proceed to use the vpe GUI.

Dragging and dropping nodes onto the graph is very slow. There's a ~0.5 second hitch from the time I let go of the mouse button until the time the node appears on the graph. Edit 2: This only happens for the first node dropped onto the graph, and only after 2+ times the vpe is run (first time is smooth).

**Comment by cboulay** [comment]
I just installed the latest NeuroPype on Windows (1.3.6) and also installed from source on Windows (using vpe from here, cpe from the download) and the issue seems to be resolved. I'll re-open if it is not resolved in Mac.

**Comment by chkothe** [comment]
Hi Chad,

yes, sorry for the sluggish response on my end -- had been going through a
long task list for our hackathon(s).
I've added some new features to the vpe in the last few commits, and there
will be quite a bunch of usability improvements coming, so I hope not too
much breaks for you if you're tracking these updates but run it against a
release version of the cpe (hope to be able to share the repo with you
sooner rather than later).

Christian
